---

- hosts: cluster_proxy
  become: yes
  become_method: sudo
  roles:
    - { role: maxscale, tags: maxscale }

- hosts: cluster_nodes
  become: yes
  become_method: sudo
  roles:
    - { role: mariadb, tags: mariadb }
